const { pool, parseBoolean } = require('./pool');
const { initializeDatabase } = require('./schema');
const {
  allocateSixDigitAor,
  resolveLineAorByLineId,
  resolveLineAorByAor,
} = require('./aor');
const {
  createUserNotification,
  getUserNotifications,
  deleteUserNotification,
} = require('./notifications');
const {
  createUser,
  findUsers,
  getUserById,
  updateUser,
  deleteUser,
  getUserByUsername,
  getUserByIdOrUsername,
  updateUserStatus,
} = require('./users');
const {
  createTenant,
  updateTenant,
  setTenantActive,
  getTenantSettings,
  updateTenantSettings,
  createSite,
  listTenants,
  getTenantByIdOrSlug,
  createSubTenant,
  listSubTenants,
  ensureTenantScaffold,
  setUserPublicFlag,
  requestTenantRelationship,
  getTenantRelationshipById,
  listTenantRelationships,
  approveTenantRelationship,
  rejectTenantRelationship,
} = require('./tenancy');
const {
  createGroup,
  findGroups,
  getGroupById,
  updateGroup,
  addUserToGroup,
  removeUserFromGroup,
  createDirectContact,
  findDirectContacts,
  getDirectContactById,
  deleteDirectContact,
} = require('./groups');
const {
  createCallSession,
  getCallSession,
  updateCallSession,
  findCallSessions,
} = require('./calls');
const {
  getLineConfiguration,
  updateLineConfiguration,
  findLineConfigurations,
} = require('./lines');
const {
  createRecording,
  getRecording,
  updateRecording,
  findRecordings,
} = require('./recordings');

module.exports = {
  pool,
  parseBoolean,
  initializeDatabase,
  allocateSixDigitAor,
  createUser,
  findUsers,
  getUserById,
  updateUser,
  deleteUser,
  createTenant,
  updateTenant,
  setTenantActive,
  getTenantSettings,
  updateTenantSettings,
  createSite,
  listTenants,
  getTenantByIdOrSlug,
  createSubTenant,
  listSubTenants,
  ensureTenantScaffold,
  setUserPublicFlag,
  requestTenantRelationship,
  getTenantRelationshipById,
  listTenantRelationships,
  approveTenantRelationship,
  rejectTenantRelationship,
  createGroup,
  findGroups,
  getGroupById,
  updateGroup,
  addUserToGroup,
  removeUserFromGroup,
  createDirectContact,
  findDirectContacts,
  getDirectContactById,
  deleteDirectContact,
  createCallSession,
  getCallSession,
  updateCallSession,
  findCallSessions,
  getLineConfiguration,
  updateLineConfiguration,
  findLineConfigurations,
  resolveLineAorByLineId,
  resolveLineAorByAor,
  createRecording,
  getRecording,
  updateRecording,
  findRecordings,
  createUserNotification,
  getUserNotifications,
  deleteUserNotification,
  getUserByUsername,
  getUserByIdOrUsername,
  updateUserStatus,
};
